spring.application.name=site

spring.datasource.url=jdbc:mysql://localhost:3306/ecomerceweb
spring.datasource.username=root
spring.datasource.password=Gustavo996

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
